/**
 * MyonVPN
 *
 * @author FantaBlueMystery, KeRn
 * @copyright 2020 by FantaBlueMystery & KeRn
 * @license http://opensource.org/licenses/lgpl-license.php LGPL - GNU Lesser General Public License
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myonvpn_tuntap_TunTapLinux */

#ifndef _Included_com_myonvpn_tuntap_TunTapLinux
#define _Included_com_myonvpn_tuntap_TunTapLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myonvpn_tuntap_TunTapLinux
 * Method:    openTun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myonvpn_tuntap_TunTapLinux_openTun
  (JNIEnv *, jobject);

/*
 * Class:     com_myonvpn_tuntap_TunTapLinux
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myonvpn_tuntap_TunTapLinux_close
  (JNIEnv *, jobject);

/*
 * Class:     com_myonvpn_tuntap_TunTapLinux
 * Method:    write
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_myonvpn_tuntap_TunTapLinux_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_myonvpn_tuntap_TunTapLinux
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_myonvpn_tuntap_TunTapLinux_read
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
